spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "https://codenames-backend-524815217558.europe-central2.run.app/login/oauth2/code/google"
          discord:

            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            scope: identify, guilds.join
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/discord"
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

discord:
  bot-token: ${DISCORD_BOT_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}
  category-id: ${DISCORD_CATEGORY_ID}

app:
  cookie:
    secure: false